### ISSUE TITLE
Just Python 3?

### ISSUE THREAD

**Issue by CarlKCarlK** [limix/bgen-reader-py#26]
Is bgen-reader just Python 3? (Fine if it is. Just wondering.)

```
(py2) carlk@kadie2:/mnt/d/OneDrive/programs/pysnptools/tests$ python
Python 2.7.16 |Anaconda, Inc.| (default, Sep 24 2019, 21:51:30)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from bgen_reader import read_bgen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/carlk/anaconda3/envs/py2/lib/python2.7/site-packages/bgen_reader/__init__.py", line 18, in <module>
    e.msg = e.msg + msg
AttributeError: 'exceptions.ImportError' object has no attribute 'msg'
>>>
```

**Comment by horta** [comment]
Yep, only Python>=3.6 I'm afraid.
