### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by cybluetree** [limix/bgen-reader-py#39]
Hi, I installed via "conda install -c conda-forge bgen-reader". When I imported it "from bgen_reader import example_filepath", I got an import error. Not sure how to fix it. Thanks!

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yc2553/miniconda3_new/envs/cy2/lib/python3.8/site-packages/bgen_reader/__init__.py", line 23, in <module>
    from ._bgen2 import open_bgen
  File "/home/yc2553/miniconda3_new/envs/cy2/lib/python3.8/site-packages/bgen_reader/_bgen2.py", line 11, in <module>
    from cbgen import bgen_file, bgen_metafile
  File "/home/yc2553/miniconda3_new/envs/cy2/lib/python3.8/site-packages/cbgen/__init__.py", line 4, in <module>
    from ._bgen_file import bgen_file
  File "/home/yc2553/miniconda3_new/envs/cy2/lib/python3.8/site-packages/cbgen/_bgen_file.py", line 11, in <module>
    from ._ffi import ffi, lib
ImportError: libathr.so.1: cannot open shared object file: No such file or directory

**Comment by chrisclarkson** [comment]
Hiya I found a way around this with:
```
git clone https://github.com/limix/bgen-reader-py
cd bgen-reader-py/
python -m pip install -e . #install directly to my conda environment
```
And then I was able to get it working

**Comment by horta** [comment]
Hi folks,

I hope the issue has now been solved with the new releases. Let me know otherwise!
