### ISSUE TITLE
Can't open bgen using symbolic links

### ISSUE THREAD

**Issue by jordanero** [limix/bgen-reader-py#42]
Hello,

I want to use the numpy inspired API to open an bgen using a symbolic link. I want to do this because I don't want to create the .metadata2.mmm file in the shared directory where the bgen lives. I thought I recalled being able to do this in a previous version of bgen-reader, but am running into the following problem now.

from bgen_reader import open_bgen
wha = open_bgen('/n/holylfs05/LABS/liang_lab_l3/Lab/jordan/ssctpr/data/ukbb_symbolic_link/ukb_imp_chr1_v3.bgen')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/n/home_fasse/jrossen/.conda/envs/ssctpr2/lib/python3.9/site-packages/bgen_reader/_bgen2.py", line 133, in __init__
    assert_file_exist(filepath)
  File "/n/home_fasse/jrossen/.conda/envs/ssctpr2/lib/python3.9/site-packages/bgen_reader/_file.py", line 14, in assert_file_exist
    raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), filepath)

I don't have a very strong understanding of how PosixPath works, but after a little playing around, it seems like PosixPath precludes the use of symbolic links.

Either allowing for the use of symbolic links, or allowing the user to specify a directory where .metadata2.mmm should be created would solve my problem completely. 

Thanks for making this software!

**Comment by CarlKCarlK** [comment]
Jordan,

Thanks for using Bgen-Reader!

I'll be able to look into this tomorrow. I wonder if you have write access to the *.bgen file's directory?

In any case, adding an option to put the *.mmm file in any directory seems like the right answer and that is likely what we'll do.


  *   Carl

From: Jordan Rossen ***@***.***>
Sent: Tuesday, June 07, 2022 7:58 AM
To: limix/bgen-reader-py ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [limix/bgen-reader-py] Can't open bgen using symbolic links (Issue #42)


Hello,

I want to use the numpy inspired API to open an bgen using a symbolic link. I want to do this because I don't want to create the .metadata2.mmm file in the shared directory where the bgen lives. I thought I recalled being able to do this in a previous version of bgen-reader, but am running into the following problem now.

from bgen_reader import open_bgen
wha = open_bgen('/n/holylfs05/LABS/liang_lab_l3/Lab/jordan/ssctpr/data/ukbb_symbolic_link/ukb_imp_chr1_v3.bgen')
Traceback (most recent call last):
File "", line 1, in
File "/n/home_fasse/jrossen/.conda/envs/ssctpr2/lib/python3.9/site-packages/bgen_reader/_bgen2.py", line 133, in init
assert_file_exist(filepath)
File "/n/home_fasse/jrossen/.conda/envs/ssctpr2/lib/python3.9/site-packages/bgen_reader/_file.py", line 14, in assert_file_exist
raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), filepath)

I don't have a very strong understanding of how PosixPath works, but after a little playing around, it seems like PosixPath precludes the use of symbolic links.

Either allowing for the use of symbolic links, or allowing the user to specify a directory where .metadata2.mmm should be created would solve my problem completely.

Thanks for making this software!

-

**Comment by CarlKCarlK** [comment]
Jordan,

Here is a possible temporary fix.

Uninstall bgen-reader (for example, pip uninstall bgen-reader)

Then install my private version from GitHub:
   pip install ***@***.***

Then you should be able to use a new 'metadata_filepath' in open_bgen. For example:

    filepath = example_filepath("example.32bits.bgen")
    with open_bgen(
        filepath, metadata_filepath=r"m:\deldir\cmk.mmm", verbose=False
    ) as bgen2:
        for num_threads in [1, 2]:
            for slice in [np.s_[:, :], np.s_[:, []]]:
                val = bgen2.read(index=slice, num_threads=num_threads)
                row_count = len(bgen2.samples[slice[0]])
                col_count = len(bgen2.ids[slice[1]])
                assert val.shape == (row_count, col_count, 3)

Please, let me know if this works for you. In any case, I'll have time tomorrow to work on it.


  *   Carl


From: Carl K
Sent: Tuesday, June 07, 2022 8:14 AM
To: limix/bgen-reader-py ***@***.***>; limix/bgen-reader-py ***@***.***>
Cc: Subscribed ***@***.***>
Subject: RE: [limix/bgen-reader-py] Can't open bgen using symbolic links (Issue #42)

Jordan,

Thanks for using Bgen-Reader!

I'll be able to look into this tomorrow. I wonder if you have write access to the *.bgen file's directory?

In any case, adding an option to put the *.mmm file in any directory seems like the right answer and that is likely what we'll do.


  *   Carl

From: Jordan Rossen ***@***.******@***.***>>
Sent: Tuesday, June 07, 2022 7:58 AM
To: limix/bgen-reader-py ***@***.******@***.***>>
Cc: Subscribed ***@***.******@***.***>>
Subject: [limix/bgen-reader-py] Can't open bgen using symbolic links (Issue #42)


Hello,

I want to use the numpy inspired API to open an bgen using a symbolic link. I want to do this because I don't want to create the .metadata2.mmm file in the shared directory where the bgen lives. I thought I recalled being able to do this in a previous version of bgen-reader, but am running into the following problem now.

from bgen_reader import open_bgen
wha = open_bgen('/n/holylfs05/LABS/liang_lab_l3/Lab/jordan/ssctpr/data/ukbb_symbolic_link/ukb_imp_chr1_v3.bgen')
Traceback (most recent call last):
File "", line 1, in
File "/n/home_fasse/jrossen/.conda/envs/ssctpr2/lib/python3.9/site-packages/bgen_reader/_bgen2.py", line 133, in init
assert_file_exist(filepath)
File "/n/home_fasse/jrossen/.conda/envs/ssctpr2/lib/python3.9/site-packages/bgen_reader/_file.py", line 14, in assert_file_exist
raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), filepath)

I don't have a very strong understanding of how PosixPath works, but after a little playing around, it seems like PosixPath precludes the use of symbolic links.

Either allowing for the use of symbolic links, or allowing the user to specify a directory where .metadata2.mmm should be created would solve my problem completely.

Thanks for making this software!

-

**Comment by jordanero** [comment]
Was there some censoring done by github? 

Your message reads:

Then install my private version from GitHub:
   pip install ***@******

**Comment by CarlKCarlK** [comment]
Try to send me an email at carlk at msn dot com
________________________________

**Comment by CarlKCarlK** [comment]
Addressed by https://github.com/limix/bgen-reader-py/pull/44

**Comment by jordanero** [comment]
Hi Carl, the update is working great! Sorry for taking so long to try it out.
I'm able to open a bgen with a metadata file in a different directory, and reuse that metadata file. 
Thanks a lot.

**Comment by CarlKCarlK** [comment]
Jordan,

That's great! (We hope to have this feature in the main version of the package soon).


  *   Carl
